### ISSUE TITLE
[Bug] The Spawn Item tab does not open

### ISSUE THREAD

**Issue by xarss** [WillWilli/PlateUpEnhancementMod#13]
When using the last version of the game and the last version of the mod, pressing F1 confirms the mod is installed but pressing F2 does nothing.  I tried updating BepInEx to its last version as well, but the only think I can use is still just pressing "J" to spawn an item.

**Comment by WillWilli** [comment]
Delete the entire BepInEx folder at steamapps\common\PlateUp\PlateUp\BepInEx and copy in the one from the latest release. 
I have just tested it myself and it is working fine. 
'J' should not longer be doing anything by default so you must still have the old version somewhere.

**Comment by xarss** [comment]
Hi! It was a mistake I did when downloading the mod! Just fixed it! Thank
you?

Sorry for this personal question, but is modding this game too hard? I love
the idea of trying to make new mods! Do you recommend something to start
modding?

Em ter., 4 de out. de 2022 às 02:20, WillWilli ***@***.***>
escreveu:

**Comment by WillWilli** [comment]
Nice one. 
If you know some C# and a bit about Unity it is not that hard. I would suggest to look at some Valheim resources as the modding community is much bigger for that game. Good luck!
