### ISSUE TITLE
Mod Seems to Break Multiplayer (Remote Play Together)

### ISSUE THREAD

**Issue by jdsandifer** [WillWilli/PlateUpEnhancementMod#17]
After installing the mod successfully, I'm having trouble getting friends to join via Remote Play Together on Steam.

In particular, it seems like the 2nd player has no control input to join the game via keyboard or controller. (I haven't yet been able to test with more players.)

Is this a known issue? If not, is there a possibility of a resolution or workaround? This is an awesome mod and I'd love to share the experience with my friends!

**Comment by WillWilli** [comment]
I have not tested Remote Play Together with this mod myself. However I have successfully used it in both Multiplayer mode and splitscreen via an app called [Parsec](https://parsec.app/).
I would have expected Remote Play Together to work but yeah maybe it doesn't... I will test it myself later. Parsec is a great app so maybe try that for now if it's still not working for you? gl

**Comment by jdsandifer** [comment]
I'll try that out. Thanks for the recommendation!

**Comment by WillWilli** [comment]
This was an issue caused by the console being open. I have disabled the console by default in latest release so hopefully it should work for you now.
