### ISSUE TITLE
[Request] Keybind for NoClip

### ISSUE THREAD

**Issue by quackedaf** [WillWilli/PlateUpEnhancementMod#18]
Activating and deactivating NoClip can be a bit of a hassle, and it would be nice to have a keybind for toggling!

**Comment by vperpl** [comment]
+1 on that make it f3 or somth

**Comment by quackedaf** [comment]
Made a fork that added this (customizable keybind) + a custom multiplier for movement speed while in NoClip 😄

**Comment by WillWilli** [comment]
Nice one dude, sorry I was meaning to do this but didn't find the time lately.
PR back into my branch if you like ;)
