### ISSUE TITLE
1.1.0 Items are not found in the 'Spawn Items' list

### ISSUE THREAD

**Issue by zyue17** [WillWilli/PlateUpEnhancementMod#21]
Hi, I believe the latest release of the enhancement mod does not support the spawning of the newer appliances such as corner grabbers and teleporters as they are not found in the list of items. Could you please add their itemIds?

**Comment by JustASysAdmin** [comment]
I second and verify this.

**Comment by WillWilli** [comment]
Thanks guys, I didn't realise there was new items in the update. Will be fixed soon.

**Comment by WillWilli** [comment]
In latest release
