### ISSUE TITLE
Install problems.

### ISSUE THREAD

**Issue by klausnstefan** [WillWilli/PlateUpEnhancementMod#26]
Hi, I have just installed this mod into my game. However, it does not work. I press F2, nothing happens. I also press F1, select debug mode and see that configuration manager is listed as a plugin with no options available. I cannot use the mod, this is up to date Bepinex and your latest release.

**Comment by WillWilli** [comment]
Hi mate, ive just tested it and its definitely working. Make sure you have the `Willi.PlateUpEnhancementMod.dll` file in this folder `steamapps\common\PlateUp\PlateUp\BepInEx\plugins\`.
If you want to send a screenshot of your folder I might be able to see whats wrong.
