### ISSUE TITLE
[bug] Blueprint desk creates infinte blueprints

### ISSUE THREAD

**Issue by boobufestuu** [WillWilli/PlateUpEnhancementMod#3]
Placing a bluprint desk will cause blueprints to spawn repetedly until the game crashs

**Comment by WillWilli** [comment]
Thanks for the report.

I can confirm I have replicated the issue. Seems a bit peculier as all other items are spawning in just fine right? Unfortunately its not possible for me to test everything so thanks for letting me know.

Ill try to resolve it asap.

**Comment by WillWilli** [comment]
Although just a question, do you really need the blueprint desk when you can spawn any other item? ;)

**Comment by boobufestuu** [comment]
I just use the mod to increase money by a little while keeping item spawns the same.

**Comment by WillWilli** [comment]
The latest release v0.1.1 fixes this issue.
