### ISSUE TITLE
Food only cards

### ISSUE THREAD

**Issue by Ty10y** [WillWilli/PlateUpEnhancementMod#32]
1. I noticed this issue for the first time after installing this mod. At the start of a new restaurant, it gives me the "Community" card (Pic below). This one isn't so bad, because I can edit the party size with the F1 menu. Just a hassle to do every 3 days. 
![Community Card](https://user-images.githubusercontent.com/25734171/203470570-ea636bc6-d7fc-411a-8319-fd3d440eb127.png)

2. The more important and maybe related issue: when it's time to pick two new cards, the options are **_always_** two new dishes. I never see any "lunch rushes" or "customers can reroll their orders" or etc anymore. This makes it _**impossible**_ to get far because there's just too many dishes to cook at once. 
![Only Food Cards](https://user-images.githubusercontent.com/25734171/203471700-a6e0e3a1-c105-4c0f-a2d4-2df23b5b47d5.png)

P.s. I love the mod! It's perfect for testing out automation ideas or for making the game easier to play. Keep up the great work!

**Comment by quackedaf** [comment]
Hello! This actually has nothing to do with mods, and the new Autumn map, instead of giving customer cards, gives two food cards including Mains! Additionally, all runs on the new Autumn map start with the new Community card (the card is specific to the autumn maps)!

**Comment by Ty10y** [comment]
OMFG I thought I was going insane! I got it again after I closed out the thread 🤣. Also do you have a link to the ChooseYourOwnCards mod? I couldn't find it anywhere.

**Comment by quackedaf** [comment]
https://github.com/Toyemaker/ChooseYourOwnCards (Or you could just play on a non-autumn map 😅 Only Autumn maps give community + 2 food cards)
