### ISSUE TITLE
Not working, help!

### ISSUE THREAD

**Issue by LukeA2494** [WillWilli/PlateUpEnhancementMod#34]
After download and following the download instructions, the mod doesnt work at all, any help please?

**Comment by WillWilli** [comment]
Can you share an image of your PlateUp folder?

**Comment by LukeA2494** [comment]
Here you go, it is the latest version of the mod as well. 
![Capture](https://user-images.githubusercontent.com/119015289/203871406-e1f9ef90-32a1-479d-bd7e-999cf8240624.PNG)

**Comment by LukeA2494** [comment]
![image](https://user-images.githubusercontent.com/119015289/203872324-e197eb38-2cca-4092-83f2-0f13f81814e9.png)
slightly better image, i realised i cut a small bit out

**Comment by WillWilli** [comment]
And you have the files `Willi.PlateUpEnhancementMod.dll` and `ConfigurationManager.dll` in '\BepInEx\plugins\" folder?
![image](https://user-images.githubusercontent.com/113902340/203878246-72aff464-3abb-4d85-bcd7-85a1559958b2.png)

Then if you press F1 in game the configuration manager should pop up.

**Comment by LukeA2494** [comment]
Yep, Im so confused why its not working haha 
![image](https://user-images.githubusercontent.com/119015289/203879886-0dedd600-0d44-45af-91c5-4e27cc8bcac1.png)

**Comment by LukeA2494** [comment]
yeah i just double checked too on the game and i go into a actual game and press F1 and nothing happens

**Comment by LukeA2494** [comment]
Whats even weirder is that the clipping through walls and walker faster is working, i just cant use the f1 and f2 feature.

**Comment by LukeA2494** [comment]
I just realised what i did wrong haha

So as im on a laptop, my f1 and f2 have a different function and just learnt that you can use the fn key to disable that. I apologise for the inconvenience, well done on the mod its really cool so far.
