### ISSUE TITLE
1.1.1 game ver

### ISSUE THREAD

**Issue by vperpl** [WillWilli/PlateUpEnhancementMod#35]
New update new items

- Autumn Event: It's the time of year for lots of food and lots of friends; in this month's event map, Autumn, you can keep out of the wind in your cosy restaurants with two twists: As your restaurant expands you'll automatically get larger and larger groups, so make sure you plan ahead and keep track of what you need. You'll also get the choice of two new dishes each time, including new mains!
- New music: The number of tracks has been doubled, with 5 new awesome tracks to play to! These are not seasonal and play in all maps. They're the work of the amazing Sam Gibbs (who also made all the other music).
- Hats: Show your love for turkeys by wearing one on your head! If that's too much for you, there's also a range of warm hats and scarves for you and your customers to wear. Also an egg.
- New wallpapers: A new set of thematic wallpapers have been added, from leaves to turkeys!
- New food: Turkey - Turkey makes a return from last year's Christmas
- New food: Nut Roast - Nut Roast also joins the fun again after a little break. Both these mains are available to unlock during gameplay on the new seasonal Autumn map
- New food: Affogato - Can't decide if you want coffee or ice cream? Then this is the dessert for you
- New food: Bread Board - Not sure what would go with plain toast on your menu? Try adding some bread as a starter
- New food: Roast Potato - Keep it simple with this side: you don't even need to peel the potato, you can leave it in its nice warm jacket
- New food: Broccoli Cheddar Soup - Another classic soup to serve your customers
- New food: Cherry Pie - A much requested dish for every menu
- Seed control: You can now choose whether seeds affect everything (like they do now) or only the layouts. This is available in the game's options menu. This means you can replay your favourite layouts and get different cards and blueprints every time
- Blueprints require pinging: You can now set the game to require you to ping blueprints on the ground to show you their info panel, to help avoid cluttering the screen for experienced players

Balance

- Dishwasher buff: The dishwasher now works faster (15s -> 10s) and is cheaper
- Extra lives: Extra lives now reset all patience bars when they trigger, giving you a full reset of everything

Fixes/Other

- You can now ping a blueprint cabinet during the day to see what's inside it
- You can now cycle forwards and backwards when selecting an outfit
- Discout desks will no longer work on cabinets with blueprints that only cost one (or zero) coins
- Daily and weekly seeds are now always the largest map size so there are two large Autumn maps available to play
- The franchise builder selection screen now wraps the card list when there are more than 10 cards available
- Fixed some more cases where customers could get stuck
- Fixed a bug with customer patience being lost when walking to a table which could cause a loss
- Colourblind labels are now sorted in the same order, so for things like ice cream it'll always be listed as CCV rather than CVC etc.
- Turkey now shows how many portions are left
- Nut roast now splits the last portion properly
- Steak extras are now labelled in colour blind mode

**Comment by WillWilli** [comment]
Is this an issue somehow?

**Comment by vperpl** [comment]
Some items were spawning as blanks but then i figured it was mod incompatibility so nah everything gucci now sir.
