### ISSUE TITLE
I press F2 but nothing pops out

### ISSUE THREAD

**Issue by synpal** [WillWilli/PlateUpEnhancementMod#37]
I press f1 and it'll pop out a menu, but f2 won't. Did I do anything wrong ?

![998](https://user-images.githubusercontent.com/50525377/204932148-6c52480c-e19b-4013-9eea-e91921e8c448.png)

**Comment by WillWilli** [comment]
Do you see options for this mod in the F1 menu?

**Comment by synpal** [comment]
> Do you see options for this mod in the F1 menu?

This?

![99](https://user-images.githubusercontent.com/50525377/204954310-d84d0e08-0758-47fd-af6f-b8ae6aedd07d.png)

**Comment by synpal** [comment]
I don't know why, but I reinstalled it and it just suddenly worked. Thank you so much.
