### ISSUE TITLE
Unable to launch Mod Window

### ISSUE THREAD

**Issue by jodronsimth** [WillWilli/PlateUpEnhancementMod#43]
F1 and F2 no longer seem to launch the mod window since the Christmas update. The mod is seemingly still active as custom shop items are still appearing, but I'm unable to open the mod window.

**Comment by pizzacat666** [comment]
Same here

**Comment by jnunez247** [comment]
PlateUp! has Creative Mode Reborn as a Workshop official mod.  lets you spawn in items for free

**Comment by WillWilli** [comment]
So the latest update seems to have broken BepInEx (what this mod uses to inject itself), not quite sure why... But I will be porting this mod to the workshop soon so lookout for that.

**Comment by WillWilli** [comment]
Update: this can be fixed by finding the BepInEx config file at `PlateUp/BepInEx/config/BepInEx.cfg`, and under [Preloader.Entrypoint] set Type = Camera, like so:
![image](https://user-images.githubusercontent.com/113902340/209416947-0d66df06-c1d0-4d76-a423-6eb759116460.png)

**Comment by jshardy** [comment]
You are freaking amazing! Thank you so much!!!

**Comment by WillWilli** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2908609256

Now on the workshop.
