### ISSUE TITLE
[Request] Steam Workshop Support

### ISSUE THREAD

**Issue by zyue17** [WillWilli/PlateUpEnhancementMod#44]
Hi, are there plans to move this mod over to Steam Workshop? It would greatly increase this mod's popularity and accessibility.

**Comment by WillWilli** [comment]
Yes, it is nearly ready. Just a bit of a delay due to Christmas stuff. Will be uploading it to the workshop soon so keep an eye out.

**Comment by zyue17** [comment]
That is terrific news! Keep up the great work my dude.
