### ISSUE TITLE
Can't get the f1 f2 menu to open

### ISSUE THREAD

**Issue by ZeroFawkesGiven** [WillWilli/PlateUpEnhancementMod#46]
I have added the mod but it doesn't seem to be working, not sure what I did wrong. Including a copy of my game file.

<img width="554" alt="plate" src="https://user-images.githubusercontent.com/123019854/213279647-c4df8bd1-8bff-4004-a622-b5c2f9e97536.PNG">

**Comment by WillWilli** [comment]
Hi mate, please use the workshop version of this mod. You can find it on the Steam workshop. I am no longer working on the Bepinex version.
I will update the readme so there is no more confusion, sorry.

**Comment by WillWilli** [comment]
Be sure to delete the Bepinex folder as it might interfere with the workshop mods.

**Comment by ZeroFawkesGiven** [comment]
Ah ok thank you.
