### ISSUE TITLE
[BUG] Shop can't spawn

### ISSUE THREAD

**Issue by alpibull** [WillWilli/PlateUpEnhancementMod#8]
I have this mod installed and can't seem spawn any item in the shop anymore. Is there any setting to set for the item to spawn?

**Comment by WillWilli** [comment]
Do you have the latest version of the mod installed (https://github.com/WillWilli/PlateUpEnhancementMod/releases/download/0.2.0/Willi.PlateUpEnhancementMod.0.2.0.zip) ? If you need to update just delete your old BepInEx folder and drag in the new one.

**Comment by vperpl** [comment]
Works fine on 1.05
